### ISSUE TITLE
How to contribute to project?

### ISSUE THREAD

**Issue by alallier** [jonhester/tvmaze#1]
Hello I'd like to be able to fork this project and add some features but i can't figure out how your GitHub source code turns into the post-processed format that the npm module has. Can you detail what build process you're using so i can hack on the module and use `npm link` on my fork to test changes? I see you have build script in `package.json` but it seems it is maybe Linux dependent? I am developing in Windows. Any help you can provide would be greatly appreciated.

**Comment by jonhester** [comment]
Yep. I develop on Linux and Mac only. I don't actually even have access to a Windows computer, but I'll see if i can come up with a fix for you. Thanks for contributing.

**Comment by jonhester** [comment]
@alallier I just made some changes in an attempt to make it work on Windows. Can you let know if it works for you?

**Comment by alallier** [comment]
Just pulled down the latest changes and tested `npm test` in Windows 7, seemed to work great! Thank you for your quick reply and resolution on this issue :)

**Comment by jonhester** [comment]
@alallier Awesome. Also, one last thing. I added automated testing so any future pull requests will get tested automatically by Travis.

**Comment by alallier** [comment]
Thanks for letting me know! Plan on sending a few more your way soon.
